-- ============================================================
--  AQUA HR SYSTEM  -  DATABASE SCHEMA  (PostgreSQL / Supabase)
--  Run this ONCE in the Supabase SQL Editor.
-- ============================================================

-- ---------- 1. EMPLOYEES (Employee Master) ----------
create table if not exists employees (
    id                  int generated by default as identity primary key,
    employee_code       text,
    full_name           text not null,
    gender              text,
    dob                 date,
    mobile              text,
    official_email      text,
    personal_email      text,
    department          text,
    designation         text,
    reporting_manager   text,
    date_of_joining     date,
    employment_type     text,
    employment_status   text,
    work_location       text,
    pan                 text,
    aadhaar             text,
    uan                 text,
    pf_no               text,
    esic_no             text,
    bank_name           text,
    account_no          text,
    ifsc                text,
    ctc                 numeric,
    notice_period       text,
    emergency_contact   text,
    emergency_phone     text,
    qualification       text,
    experience_years    numeric,
    skills              text,
    last_appraisal      text,
    next_appraisal      text,
    leave_balance       numeric,
    remarks             text,
    created_at          timestamptz default now(),
    updated_at          timestamptz default now()
);

-- ---------- 2. LEAVE RECORDS (Leave Tracker summary) ----------
create table if not exists leave_records (
    id            int generated by default as identity primary key,
    employee_id   int not null references employees(id) on delete cascade,
    period        text default to_char(now(),'YYYY'),
    cl            numeric,
    sl            numeric,
    leave_taken   numeric,
    balance       numeric,
    wfh           numeric,
    notes         text,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now()
);

-- ---------- 3. ATTENDANCE ----------
create table if not exists attendance (
    id            int generated by default as identity primary key,
    employee_id   int not null references employees(id) on delete cascade,
    month         text,
    present       numeric,
    absent        numeric,
    late          numeric,
    wfh           numeric,
    overtime      numeric,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now()
);

-- ---------- 4. PAYROLL ----------
create table if not exists payroll (
    id            int generated by default as identity primary key,
    employee_id   int not null references employees(id) on delete cascade,
    period        text default to_char(now(),'YYYY-MM'),
    gross         numeric,
    pf            text,
    esic          text,
    tds           text,
    deductions    text,
    net_salary    numeric,
    payment_date  text,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now()
);

-- ---------- 5. DOCUMENTS ----------
create table if not exists documents (
    id                  int generated by default as identity primary key,
    employee_id         int not null references employees(id) on delete cascade,
    pan                 text,
    aadhaar             text,
    photo               text,
    education           text,
    experience          text,
    bank_proof          text,
    offer_letter        text,
    appointment_letter  text,
    created_at          timestamptz default now(),
    updated_at          timestamptz default now()
);

-- ---------- 6. USERS (logins: MD / HR / Employee) ----------
create table if not exists users (
    id             int generated by default as identity primary key,
    username       text unique not null,
    full_name      text,
    email          text,
    password_hash  text not null,
    role           text not null check (role in ('MD','HR','Employee')),
    employee_id    int references employees(id) on delete set null,
    is_active      boolean default true,
    created_at     timestamptz default now()
);

-- ---------- 7. LEAVE REQUESTS (employee self-service + approval) ----------
create table if not exists leave_requests (
    id            int generated by default as identity primary key,
    employee_id   int not null references employees(id) on delete cascade,
    leave_type    text,
    from_date     date,
    to_date       date,
    num_days      numeric,
    reason        text,
    status        text default 'Pending' check (status in ('Pending','Approved','Rejected')),
    decided_by    text,
    decided_at    timestamptz,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now()
);

-- ---------- 8. COMPLAINTS / FEEDBACK (also profile-correction requests) ----------
create table if not exists complaints (
    id            int generated by default as identity primary key,
    employee_id   int references employees(id) on delete set null,
    submitted_by  text,
    category      text,
    subject       text,
    message       text,
    status        text default 'Open' check (status in ('Open','In Progress','Resolved','Closed')),
    response      text,
    resolved_by   text,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now()
);

-- ---------- 9. NOTICE BOARD ----------
create table if not exists notices (
    id            int generated by default as identity primary key,
    title         text not null,
    body          text,
    posted_by     text,
    is_active     boolean default true,
    created_at    timestamptz default now(),
    updated_at    timestamptz default now()
);

-- ---------- 10. AUDIT LOG ----------
create table if not exists audit_log (
    id           bigint generated by default as identity primary key,
    action_time  timestamptz default now(),
    app_user     text,
    action       text,
    table_name   text,
    record_id    text,
    field_name   text,
    old_value    text,
    new_value    text
);

-- ============================================================
--  AUDIT TRIGGER  -  logs every INSERT / UPDATE / DELETE
-- ============================================================
create or replace function log_audit() returns trigger as $$
declare
    actor  text := coalesce(current_setting('app.current_user', true), 'system');
    rec_id text;
    k      text;
    oldj   jsonb;
    newj   jsonb;
begin
    if (tg_op = 'DELETE') then
        oldj   := to_jsonb(old);
        rec_id := coalesce(oldj->>'id','');
        insert into audit_log(app_user, action, table_name, record_id, field_name, old_value, new_value)
        values (actor, 'DELETE', tg_table_name, rec_id, null, oldj::text, null);
        return old;
    elsif (tg_op = 'INSERT') then
        newj   := to_jsonb(new);
        rec_id := coalesce(newj->>'id','');
        insert into audit_log(app_user, action, table_name, record_id, field_name, old_value, new_value)
        values (actor, 'INSERT', tg_table_name, rec_id, null, null, newj::text);
        return new;
    else
        oldj := to_jsonb(old);
        newj := to_jsonb(new);
        rec_id := coalesce(newj->>'id','');
        for k in select jsonb_object_keys(newj) loop
            if (oldj->>k) is distinct from (newj->>k)
               and k not in ('updated_at','created_at') then
                insert into audit_log(app_user, action, table_name, record_id, field_name, old_value, new_value)
                values (actor, 'UPDATE', tg_table_name, rec_id, k, oldj->>k, newj->>k);
            end if;
        end loop;
        return new;
    end if;
end;
$$ language plpgsql;

create or replace function touch_updated_at() returns trigger as $$
begin
    new.updated_at := now();
    return new;
end;
$$ language plpgsql;

-- attach audit + touch triggers to all data tables
do $$
declare t text;
begin
    foreach t in array array['employees','leave_records','attendance','payroll',
                             'documents','leave_requests','complaints','notices'] loop
        execute format('drop trigger if exists trg_audit_%1$s on %1$s', t);
        execute format('create trigger trg_audit_%1$s after insert or update or delete on %1$s
                        for each row execute function log_audit()', t);
        execute format('drop trigger if exists trg_touch_%1$s on %1$s', t);
        execute format('create trigger trg_touch_%1$s before update on %1$s
                        for each row execute function touch_updated_at()', t);
    end loop;
end $$;

-- ============================================================
--  DONE. Next: run scripts/seed_users.py then scripts/migrate_excel.py
-- ============================================================
